service:
  type: LoadBalancer

adminUser: admin
adminPassword: admin123

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        options:
          path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    kubernetes-cluster:
      json: |
        {
          "annotations": {
            "list": []
          },
          "editable": true,
          "gnetId": null,
          "graphTooltip": 0,
          "id": null,
          "panels": [],
          "schemaVersion": 16,
          "title": "Kubernetes Cluster Overview",
          "version": 0
        }
